#!/bin/bash
#------------------------------------------------------------------------------
base=$BUILD_BASE
 pkg=Stntuple
list_of_subpackages="alg ana base geom gui loop mod obj print val"
#------------------------------------------------------------------------------
# Stntuple and its subpackages
#------------------------------------------------------------------------------
if [ ! -d $base/include/$pkg ] ; then
    echo pwd=$pwd ; creating $base/include/$pkg
    mkdir -p $base/include/$pkg ;
fi

for d in $list_of_subpackages ; do
    if [[ -e $base/$pkg/$d ]] && [[ ! -e $base/include/$pkg/$d ]] ; then 
	echo `pwd`/$0 : creating symbolic link $base/include/$pkg/$d
	ln -s ../../$pkg/$d/$d $base/include/$pkg/$d
    fi
done
#------------------------------------------------------------------------------
# SCons-related things: executed from Stntuple
# execution in Stntuple
#------------------------------------------------------------------------------
if [ ! -d ../site_scons ] ; then mkdir ../site_scons ; fi
cp -u scripts/site_init.py             ../site_scons/.
cp -u scripts/stntuple_helper.py       ../site_scons/.
#------------------------------------------------------------------------------
# .rootrc and rootlogon.C could be modified by the user, copy them just once
#------------------------------------------------------------------------------
if [ ! -f ../.rootrc     ] ; then cp scripts/.rootrc     ../. ; fi
if [ ! -f ../rootlogon.C ] ; then cp scripts/rootlogon.C ../. ; fi
