#!/bin/bash
#------------------------------------------------------------------------------
# create a prototype of a user analysis package by cloning and renaming templates 
# from Stntuple/ana 
# call format:  
#                 make_analysis_package [pkg]
#
#  pkg : name of the user analysis package to be created, default: aaa
#------------------------------------------------------------------------------
pkg=aaa # $USER

if [ ".$1" != "." ] ; then pkg=$1 ; fi

if [ -d $pkg ] ; then 
    echo package $pkg already exists, do the cleanup first.
    exit
fi

mkdir -p $pkg/ana/ana/dict
mkdir -p $pkg/ana/scripts
mkdir -p $pkg/scripts

#------------------------------------------------------------------------------
# populate
#------------------------------------------------------------------------------
cp Stntuple/SConscript     $pkg/
cp Stntuple/ana/SConscript $pkg/ana

cat Stntuple/scripts/build_config  | grep -v site_scons | grep -v .rootrc | grep -v rootlogon | \
    sed "s/Stntuple/$pkg/g" \
    | awk -F = '{if ($1 == "list_of_subpackages") { print "list_of_subpackages=\"ana\""} else {print $0}}' \
    >| $pkg/scripts/build_config

chmod 755 $pkg/scripts/build_config
#------------------------------------------------------------------------------
# copy modules
#------------------------------------------------------------------------------
declare -a modules
declare -a scripts
declare -a m_names

modules=(ClusterAna    CrvAna GenAna HelixAna SpmcAna TrackAna TrackSeedAna TriggerAna )
scripts=(calorimeter.C crv.C  genp.C helix.C  spmc.C  trk.C    trs.C        trigger.C  )
m_names=(m_cls         m_crv  m_gen  m_hel    m_spmc  m_trk    m_trs        m_trig     )
#------------------------------------------------------------------------------
# step 2 : copy modules, rename, replace the namespace
#------------------------------------------------------------------------------
# echo "----->"  step 2
for m in ${modules[@]}; do
    module=T${m}Module

    cat Stntuple/ana/$module.cc | sed "s/stntuple::/$pkg::/g" | \
	sed "s#Stntuple/ana#${pkg}/ana#"                      | \
	awk -v pkg=$pkg '{if ($1 == "namespace") {print $1 " " pkg " {" } else { print $0}}' \
	>| $pkg/ana/$module.cc

    cat Stntuple/ana/ana/$module.hh | sed "s/Stntuple_ana/${pkg}_ana/" | sed "s/stntuple::/$pkg::/g" | \
	sed "s#Stntuple/ana#$pkg/ana#"  | \
	awk -v pkg=$pkg '{if ($1 == "namespace") {print $1 " " pkg " {" } else { print $0}}' \
	>| $pkg/ana/ana/$module.hh

    cat Stntuple/ana/ana/dict/${module}_linkdef.h | sed "s/stntuple::/$pkg::/g" \
	>| $pkg/ana/ana/dict/${module}_linkdef.h
done
#------------------------------------------------------------------------------
# step 2.5 : copy data structures, to decouple the clone from Stntuple/ana
#------------------------------------------------------------------------------
list_of_includes="AnaDefs.hh HistBase_t.h TrackPar_t.hh ParBase_t.hh TrackParBase_t.hh"
# echo "----->"  step 2.5
for f in $list_of_includes; do
    cat Stntuple/ana/ana/$f | sed "s/Stntuple_ana/${pkg}_ana/" | sed "s/stntuple::/$pkg::/g" |   \
	sed "s#Stntuple/ana#${pkg}/ana#"  | \
	awk -v pkg=$pkg '{if ($1 == "namespace") {print $1 " " pkg " {" } else { print $0}}' \
	>| $pkg/ana/ana/${f}_tmp

    mv $pkg/ana/ana/${f}_tmp $pkg/ana/ana/$f
done

# echo "----->"  step 3
source $pkg/scripts/build_config
#------------------------------------------------------------------------------
# modules.hh
#------------------------------------------------------------------------------
echo "----->"  step 4
echo "#ifndef ${pkg}_ana_scripts_modules_hh" >| $pkg/ana/scripts/modules.hh 
echo "#define ${pkg}_ana_scripts_modules_hh" >> $pkg/ana/scripts/modules.hh 

for i in ${!modules[@]}; do
    module=$pkg::${modules[$i]}Module
    # echo  "class $module;"                                                >> $pkg/ana/scripts/modules.hh 
    printf "%-30s %-8s %-10s\n" "${module}*" "${m_names[$i]}" " = NULL;" >> $pkg/ana/scripts/modules.hh 
done

# echo "#endif" >> $pkg/ana/scripts/modules.hh 
#------------------------------------------------------------------------------
# load_${pkg}_scripts.C
#------------------------------------------------------------------------------
# echo "----->"  step 5
echo "#include \"TInterpreter.h\""                >| $pkg/ana/scripts/load_stnana_scripts_$pkg.C
echo "#include \"${pkg}/ana/scripts/modules.hh\"" >> $pkg/ana/scripts/load_stnana_scripts_$pkg.C
echo "int load_stnana_scripts_${pkg}() {"         >> $pkg/ana/scripts/load_stnana_scripts_$pkg.C
cat << "EOF"                                      >> $pkg/ana/scripts/load_stnana_scripts_$pkg.C
//-----------------------------------------------------------------------------
// the first parameter is the script, the second - env.var telling whether 
// the script has to be loaded. If the corresponding env. variable is not defined,
// the script is not loaded. PWD is always defined
//-----------------------------------------------------------------------------
  char        macro[200];

  const char* script[] = { 
    "calorimeter.C", "PWD",
    "crv.C"        , "PWD",
    "genp.C"       , "PWD",
    "trk.C"        , "PWD",
    "trs.C"        , "PWD",
    "trigger.C"    , "PWD",
    "helix.C"      , "PWD",
    0 
  };

  TString work_dir = gEnv->GetValue("Stnana.TestReleaseDir",gSystem->Getenv("PWD"));

  TInterpreter* cint = gROOT->GetInterpreter();
  
  for (int i=0; script[i] != 0; i+=2) {
    const char* dir = gSystem->Getenv(script[i+1]);
    if (dir) {
EOF
echo "      sprintf(macro,\"%s/$pkg/ana/scripts/%s\",dir,script[i]);" >> $pkg/ana/scripts/load_stnana_scripts_$pkg.C
cat << "EOF" >> $pkg/ana/scripts/load_stnana_scripts_$pkg.C
      if (! cint->IsLoaded(macro)) cint->LoadMacro(macro);
    }
  }
  
  return 0;
}
EOF

#------------------------------------------------------------------------------
# copy individual job configuration scripts
#------------------------------------------------------------------------------
for i in ${!scripts[@]} ; do
    script=${scripts[$i]}
    f1=Stntuple/ana/scripts/$script
    f2=$pkg/ana/scripts/$script

    module=${modules[$i]}

    m1=Stn${module}
    m2=My${module}

    cat $f1 | \
	sed "s#Stntuple/ana#$pkg/ana#g" | sed "s/stn_//g" | \
	sed "s/$m1/$m2/g" | \
	sed "s/stntuple::/$pkg::/g" >| $f2
done
#------------------------------------------------------------------------------
# modify .rootrc and rootlogon.C to include new package
#------------------------------------------------------------------------------
if [ ".`cat .rootrc | grep +Stnana.Package | grep $pkg`" == '.' ] ; then 
  echo "+Stnana.Package                $pkg" >> .rootrc
fi

cat rootlogon.C | awk -v pkg=$pkg '
{ if ($1 == "//insert_user_libs_here") printf("      gSystem->Load(\"lib/lib%s_ana.so\");\n",pkg) ;
  else print $0; 
  endif 
}' >| rootlogon.C.new ; mv  rootlogon.C.new rootlogon.C
#------------------------------------------------------------------------------
# finally, run build_config
#------------------------------------------------------------------------------
source $pkg/scripts/build_config
echo package $pkg successfully created
