#!/bin/bash
#------------------------------------------------------------------------------
# creates catalog of a given book 
# example: . ./update_book_catalog bluearc 
# explicitly account for the presence of <b> and </b> tags in the dataset name in 
# the dataset description string
# special files: 
#
#  1. $book_dir/AAA_DESCRIPTION.html - sourced into the catalog in the end
#  2. $book_dir/AAA_DESCRIPTION.$version.html - sourced into the catalog for dataset of a given version
#------------------------------------------------------------------------------
       books=$1
     top_dir=/web/sites/mu2e.fnal.gov/htdocs/atwork/computing/Stntuple/cafdfc

if [ ".$books" == "." ] ; then
    dirs=`ls -d $top_dir/*/`
    books=`for d in $dirs ; do echo $d | awk -F/ '{print $(NF-1)}'; done`
fi

echo `date` : updating books=$books

for book in $books ; do

    dir=$top_dir/$book

    HTML_CATALOG=$dir/index.shtml
# echo HTML_CATALOG:$HTML_CATALOG
#------------------------------------------------------------------------------
# form book catalog header
#------------------------------------------------------------------------------
    echo "<!--#set var=\"pagetitle\" value=\"STNTUPLE datasets\" -->"         >| $HTML_CATALOG
    echo "<!--#include virtual=\"/includes/mu2e_top.shtml\" -->"              >> $HTML_CATALOG

    echo "<!-- End of header:  Put your html below this comment. -->"         >> $HTML_CATALOG
    echo "<p>"                                                                >> $HTML_CATALOG

    echo "STNTUPLE datasets , book = <b>$book</b> <br> <br>"                  >> $HTML_CATALOG

    echo "<body style=\"font-family:monospace;\">"                            >> $HTML_CATALOG

    echo "<style type=\"text\css\">"                                          >> $HTML_CATALOG
    echo "span {"                                                             >> $HTML_CATALOG
    echo "display: inline-block;"                                             >> $HTML_CATALOG
    echo "width: 200px;"                                                      >> $HTML_CATALOG
    echo "}"                                                                  >> $HTML_CATALOG
    echo "</style>"                                                           >> $HTML_CATALOG
#------------------------------------------------------------------------------
# loop over datasets
#------------------------------------------------------------------------------
    echo "<ul>"                                                               >> $HTML_CATALOG

#    cmd="ls -al $dir | grep -v AAA_ | grep -v index.shtml | awk '{if ((substr(\$9,0,1) != \".\") && (substr(\$9,0,1) != \"\")) print \$9}' | sort -k1.7,8" 
#    cmd="ls -l $dir | grep -v AAA_ | grep -v index.shtml | cut -c48-55 | sort -k1.7,8" 

    versions=`ls -d $dir/* | grep -v AAA_ | grep -v index.shtml | awk -F/ '{print $NF}' | cut -c5-8 | sort -k1.7,8 | uniq`
    #echo versions=$versions

    list_of_datasets=`ls -d $dir/* | grep -v AAA_ | grep -v index.shtml | awk -F/ '{print $NF}' | sort -k1.7,8`
    # echo list_of_datasets=$list_of_datasets
    
    for version in $versions ; do

	if [ -f $dir/AAA_DESCRIPTION.$version.html ] ; then
	    cat $dir/AAA_DESCRIPTION.$version.html                            >> $HTML_CATALOG 
	else
	    echo "<p> <li> datasets version $version <p>"                     >> $HTML_CATALOG
	fi

	list_of_datasets=`ls -d $dir/* | grep -v AAA_ | grep -v index.shtml | awk -F/ '{print $NF}' | grep $version | sort -k1.7,8`
	# echo datasets:$list_of_datasets

	for f in $list_of_datasets ; do 
#------------------------------------------------------------------------------
# find fileset-level catalog of a dataset
#------------------------------------------------------------------------------
            catalog=$dir/$f/AAA_CATALOG.html
    #    echo catalog:$catalog
            description=`cat $catalog | grep "# :DESCRIPTION:" | sed 's/# :DESCRIPTION://'`
            offline_ver=`cat $catalog | grep "# :OFFLINE_VERSION:" | sed 's/# :OFFLINE_VERSION://'`
            if [ ".$offline_ver" == "." ] ; then offline_ver="......" ; fi
            len0=${#description}
            des1=`echo $description | sed 's#<b>##' |  sed 's#</b>##'`
            len1=${#des1}
            description=$description".........................................................."
            description=$description"..............................................."
            ldesc=$((99+$len0-$len1)) 
#------------------------------------------------------------------------------
# see if there is a dataset description file - AAA_DESCRIPTION.html
#------------------------------------------------------------------------------
            if [ -f $dir/$f/AAA_DESCRIPTION.html ] ; then
    		text=" see <a href=$f/AAA_DESCRIPTION.html> detailed description of the dataset </a>"
            else
    		text=" see more details in the fileset catalog ........."
            fi
            dsname=$f" ..................."
            ov=`printf "%6s" $offline_ver`
            echo "<li> <a href=$f/AAA_CATALOG.html width=200px>${dsname:0:12}</a> | <a href=$f/AAA_FILES.txt> files </a> | $ov | ${description:0:$ldesc} | $text" >> $HTML_CATALOG ; 
	done
    done
#------------------------------------------------------------------------------
# form catalog trailer
#------------------------------------------------------------------------------
      echo "</ul>"                                                            >> $HTML_CATALOG
#------------------------------------------------------------------------------
# if $book/AAA_DESCRIPTION.html exists, append it to the book catalog
#------------------------------------------------------------------------------
      if [ -f $dir/AAA_DESCRIPTION.html ] ; then
	  cat $dir/AAA_DESCRIPTION.html                                       >> $HTML_CATALOG
      fi
      echo "<body style=\"\" >"                                               >> $HTML_CATALOG
      echo " <a href=https://mu2einternalwiki.fnal.gov/wiki/Stntuple-Datasets>back to the top catalog page</a>"         >> $HTML_CATALOG
      
      echo "<!-- Start of footer:  End your html before this comment. -->"    >> $HTML_CATALOG
      echo "<!--#set var=\"contact\" value=\"kutschke@fnal.gov\" -->"         >> $HTML_CATALOG
      echo "<!--#include virtual=\"/includes/mu2e_footer.shtml\" -->"         >> $HTML_CATALOG
done
