#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
rootlibs = env['ROOTLIBS']
if ( not ("EG" in rootlibs)):
    rootlibs.insert(rootlibs.index("Physics")+1,"EG");

debug  = False
# env.Append(FORTRANFLAGS = ['-Iinclude','-g']);
env.Append(FORTRANFLAGS = ['-Iinclude']);
helper = stntuple_helper(env,debug);

helper.handle_dictionaries();

list_of_fortran_files = Glob('*.f',strings=True);
list_of_cc_files      = Glob('*.cc', strings=True);
skip_list             = []
libs                  = ['Stntuple_obj', 'Stntuple_base', rootlibs, 'gfortran'];

helper.compile_fortran(list_of_fortran_files,skip_list);

helper.build_libs(list_of_cc_files,skip_list,libs);

# print "tmpdir:"+env['TMP_LIB_DIR']
